# 异常

捕获异常

```scala
package com.stanlong.scala

/**
 * 捕获异常
 */
object Exercise01 {
    def main(args: Array[String]): Unit = {
        try{
            var r = 1 / 0
        }catch{
            case ex: ArithmeticException=> println("捕获了除数为零的算数异常")
            case ex: Exception => {
                println("捕获了异常")
            }
        }finally {
            // 一定要执行的代码
            println("scala finally...")
        }
    }

}
```

抛出异常

```scala
package com.stanlong.scala

/**
 * 抛出异常
 */
object Exercise01 {
    def main(args: Array[String]): Unit = {
        val result = test()
        println(result.toString)
    }

    def test(): Nothing={
        throw new Exception("出现异常")
    }

}
```

异常注解

```scala
package com.stanlong.scala

/**
 * 异常注解
 */
object Exercise01 {
    def main(args: Array[String]): Unit = {
        f11()
    }

    @throws(classOf[NumberFormatException])
    def f11(): Unit ={
        "abc".toInt
    }

}
```

